version: "3.7"
services:
  master:
    image: mysql:8
    container_name: master
    ports:
      - 3306:3306
    volumes:
    - "./master.cnf:/etc/mysql/conf.d/master.cnf"
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      projector:
        ipv4_address: 10.0.0.10

  slave1:
    image: mysql:8
    container_name: slave1
    volumes:
    - "./slave1.cnf:/etc/mysql/conf.d/slave1.cnf"
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      projector:
        ipv4_address: 10.0.0.11

  slave2:
    image: mysql:8
    container_name: slave2
    volumes:
    - "./slave2.cnf:/etc/mysql/conf.d/slave2.cnf"
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      projector:
        ipv4_address: 10.0.0.12

networks:
  projector:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24